#
# eco
# by Auxilor
#

mysql:
  enabled: false # Set to false, data.yml will be used instead.
  host: localhost
  port: 3306
  database: database
  user: username
  password: passy

autosave:
  ticks: 20000 # The amount of ticks between autosaves
  log: false # If auto-save messages should be sent to console
  async: false # If saves should be performed asynchronously. May cause bugs without MySQL


# Options to fix villager bugs left behind from old (buggy) versions.
villager-display-fix: false

# DropQueue by default uses a faster collated queue system where all drops
# that originate from the same player on the same tick are dropped together.
# Disable it if it changes drop mechanics too much for you.
use-fast-collated-drops: true

# bStats is important and you should keep it enabled.
# This option is only here because of compliance with data protection laws.
enable-bstats: true

# Some plugins use their own item display systems (eg Triton)
# And must be run after eco. Don't enable this unless you run a conflicting plugin
# and have been told to enable it.
use-lower-protocollib-priority: false

# Display frames massively optimize PacketWindowItems, however some users have
# reported display bugs by using it. If you have any problems with it, then you
# should disable this option.
use-display-frame: true

# Time to live for a display frame. In other words, this is how frequent (in ticks)
# that display frames will be cleared / deleted.
display-frame-ttl: 17

# Window items packets have the option to be run asynchronously. This may cause
# some bugs and is considered experimental, however it has been tested without
# any apparent issues. Enable this if performance is absolutely crucial or if you
# are experiencing severe display lag.
async-display:
  # If async display should always be used.
  enabled: false

  # Log errors that occur in async processing.
  log-errors: true

  # If the server is running under heavy load (below a certain TPS value), enable
  # async display automatically. This can prevent some server crashes under load.
  emergency:
    # If emergency async should be used.
    enabled: true
    # Below this TPS value, emergency async display will be used.
    cutoff: 18

  # If players with a large amount of display packets should have their processing
  # done asynchronously. This will help if a player is trying to crash the server
  # by overloading the display system.
  ratelimit:
    # If rate limit async display should be used.
    enabled: true
    # The amount of window items packets per timeframe needed to enable async display
    # for a specified player.
    cutoff: 5
    # The length of the timeframe in seconds.
    # Cutoff 5, Timeframe 1 means that if there are more than 5 window items packets
    # being sent per second for a player, then that player should have their packets
    # handled asynchronously.
    timeframe: 1