#
# eco
# by Auxilor
#


# Options to fix villager bugs left behind from old (buggy) versions.
villager-display-fix: false

# DropQueue by default uses a faster collated queue system where all drops
# that originate from the same player on the same tick are dropped together.
# Disable it if it changes drop mechanics too much for you.
use-fast-collated-drops: true

# bStats is important and you should keep it enabled.
# This option is only here because of compliance with data protection laws.
enable-bstats: true

# Some plugins use their own item display systems (eg Triton)
# And must be ran after eco. Don't enable this unless you run a conflicting plugin
# and have been told to enable it.
use-lower-protocollib-priority: false

# Display frames massively optimize PacketWindowItems, however some users have
# reported display bugs by using it. If you have any problems with it, then you
# should disable this option.
use-display-frame: true

# Time to live for a display frame. In other words, this is how frequent (in ticks)
# that display frames will be cleared / deleted.
display-frame-ttl: 17