name: eco
version: ${projectVersion}
main: com.willfp.eco.internal.spigot.EcoHandler
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - Vulcan
  - PlaceholderAPI
  - mcMMO
  - CombatLogX
  - ShopGUIPlus
  - ItemsAdder
  - Oraxen
  - HeadDatabase
  - Multiverse-Inventories
  - Alice
  - HolographicDisplays
  - GHolo
  - CMI
  - Essentials
  - Vault
  - BentoBox
  - DeluxeCombat
  - IridiumSkyblock
  - SuperiorSkyblock2
  - CrashClaim
  - DecentHolograms
  - MythicMobs
  - CustomCrafting
  - ExecutableItems
  - RPGHorses
libraries:
  - 'org.reflections:reflections:0.9.12'
  - 'org.apache.maven:maven-artifact:3.0.3'
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
  - 'net.kyori:adventure-platform-bukkit:4.0.0'
  - 'net.kyori:adventure-api:4.9.3'
  - 'net.kyori:adventure-text-serializer-gson:4.9.3'
  - 'net.kyori:adventure-text-serializer-legacy:4.9.3'
  - 'org.jetbrains.exposed:exposed-core:0.37.3'
  - 'org.jetbrains.exposed:exposed-dao:0.37.3'
  - 'org.jetbrains.exposed:exposed-jdbc:0.37.3'
  - 'mysql:mysql-connector-java:8.0.25'
  - 'com.google.guava:guava:31.0.1-jre'
  - 'com.zaxxer:HikariCP:5.0.0'
  - 'org.objenesis:objenesis:3.2'
  - 'com.github.ben-manes.caffeine:caffeine:3.0.5'