name: eco
version: ${projectVersion}
main: com.willfp.eco.internal.spigot.EcoHandler
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - Vulcan
  - PlaceholderAPI
  - mcMMO
  - CombatLogX
  - ShopGUIPlus
  - ItemsAdder
  - Oraxen
  - HeadDatabase
  - Multiverse-Inventories
  - Alice
  - HolographicDisplays
  - GHolo
  - CMI
  - Essentials
  - Vault
  - BentoBox
  - DeluxeCombat
  - IridiumSkyblock
  - SuperiorSkyblock2
  - CrashClaim
  - DecentHolograms
  - MythicMobs
  - CustomCrafting
  - ExecutableItems
  - RPGHorses
libraries: # Stuck using lib-loader for these
  - "net.kyori:adventure-api:4.10.1"
  - "net.kyori:adventure-text-serializer-gson:4.10.1"
  - "net.kyori:adventure-text-serializer-legacy:4.10.1"