name: eco
version: ${projectVersion}
main: com.willfp.eco.spigot.EcoPlugin
api-version: 1.15
authors: [Auxilor]
website: willfp.com
loadbefore:
  - EcoEnchants
  - Talismans
  - StatTrackers
  - EcoArmor
  - EcoBosses
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO
  - ULands
  - CombatLogX