name: eco
version: ${projectVersion}
main: com.willfp.eco.spigot.EcoHandler
api-version: 1.16
authors: [Auxilor]
website: willfp.com
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO
  - CombatLogX
libraries:
  - org.reflections:reflections:0.9.12
  - org.apache.maven:maven-artifact:3.0.3
  - net.kyori:adventure-text-serializer-gson:4.8.1
  - net.kyori:adventure-text-serializer-legacy:4.8.1
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21